# Generated by Django 6.0.6 on 2026-07-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='payment',
            field=models.CharField(choices=[('PAY', 'Payed'), ('NP', 'NotPaid')], default='NP', max_length=3),
        ),
    ]
