# Generated by Django 6.0.6 on 2026-07-18 16:51

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 7, 18, 16, 51, 32, 437172, tzinfo=datetime.timezone.utc), verbose_name='زمان انتشار'),
        ),
    ]
