# Generated by Django 6.0.6 on 2026-07-18 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 18, 17, 4, 51, 497050, tzinfo=datetime.timezone.utc)),
        ),
    ]
