# Generated by Django 6.0.6 on 2026-07-18 17:05

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 7, 18, 17, 5, 57, 456896, tzinfo=datetime.timezone.utc)),
        ),
    ]
