# Generated by Django 6.0.6 on 2026-07-24 07:09

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('subject', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'تیکت ها',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 7, 24, 7, 9, 36, 583509, tzinfo=datetime.timezone.utc)),
        ),
    ]
