# Generated by Django 6.0.6 on 2026-07-24 07:21

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_ticket_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 7, 24, 7, 21, 54, 203956, tzinfo=datetime.timezone.utc)),
        ),
    ]
