# Generated by Django 6.0.6 on 2026-07-26 15:59

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 7, 26, 15, 59, 41, 149235, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='پیام')),
                ('name', models.CharField(max_length=250, verbose_name='اسم')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان آپدیت')),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'verbose_name': ' کامنت ها ',
                'verbose_name_plural': ' کامنت ها ',
                'ordering': ('created',),
                'indexes': [models.Index(fields=['created'], name='blog_commen_created_0e6ed4_idx')],
            },
        ),
    ]
