# Generated by Django 6.0.6 on 2026-07-27 05:11

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_comment_active_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 7, 27, 5, 11, 30, 565006, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 7, 27, 5, 11, 30, 562615, tzinfo=datetime.timezone.utc)),
        ),
    ]
