# Generated by Django 6.0.6 on 2026-07-27 05:11

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_comment_published_alter_post_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='published',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 7, 27, 5, 11, 55, 651280, tzinfo=datetime.timezone.utc)),
        ),
    ]
