# Generated by Django 6.0.8 on 2026-08-05 20:12

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_reading_time_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2026, 8, 5, 20, 12, 33, 60063, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.CharField(default=0, verbose_name='زمان مطالعه'),
        ),
    ]
